apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysetlist-hpa
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysetlist-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  - type: Pods
    pods:
      metric:
        name: response_time_95th_percentile
      target:
        type: AverageValue
        averageValue: "500m" # 500ms
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300 # 5 minutes
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600 # 10 minutes
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min

---
# Vertical Pod Autoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mysetlist-vpa
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: autoscaling
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysetlist-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: mysetlist-app
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysetlist-pdb
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mysetlist
      component: frontend

---
# Network Policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysetlist-network-policy
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: security
spec:
  podSelector:
    matchLabels:
      app: mysetlist
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from nginx ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  # Allow traffic from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: mysetlist-monitoring
    ports:
    - protocol: TCP
      port: 3000
  # Allow traffic within the same namespace
  - from:
    - podSelector:
        matchLabels:
          app: mysetlist
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS traffic to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP traffic to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow Supabase connection
  - to: []
    ports:
    - protocol: TCP
      port: 5432

---
# Resource Quota for namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mysetlist-resource-quota
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: resource-management
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
    count/deployments.apps: "10"
    count/jobs.batch: "10"

---
# Limit Range for individual pods
apiVersion: v1
kind: LimitRange
metadata:
  name: mysetlist-limit-range
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: resource-management
spec:
  limits:
  - type: Pod
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: Container
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi