# Secret Template - DO NOT COMMIT ACTUAL VALUES
# Use sealed-secrets or external secret management in production

apiVersion: v1
kind: Secret
metadata:
  name: mysetlist-secrets
  namespace: mysetlist-production
  labels:
    app: mysetlist
    component: secrets
  annotations:
    description: "MySetlist production secrets - use external secret management"
type: Opaque
stringData:
  # Supabase Configuration
  supabase-url: "REPLACE_WITH_ACTUAL_SUPABASE_URL"
  supabase-anon-key: "REPLACE_WITH_ACTUAL_SUPABASE_ANON_KEY"
  supabase-service-role-key: "REPLACE_WITH_ACTUAL_SUPABASE_SERVICE_ROLE_KEY"
  
  # External API Keys
  spotify-client-id: "REPLACE_WITH_ACTUAL_SPOTIFY_CLIENT_ID"
  spotify-client-secret: "REPLACE_WITH_ACTUAL_SPOTIFY_CLIENT_SECRET"
  ticketmaster-api-key: "REPLACE_WITH_ACTUAL_TICKETMASTER_API_KEY"
  setlistfm-api-key: "REPLACE_WITH_ACTUAL_SETLISTFM_API_KEY"
  
  # Application Secrets
  jwt-secret: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  cron-secret: "REPLACE_WITH_ACTUAL_CRON_SECRET"
  
  # Database credentials (if using external database)
  database-url: "REPLACE_WITH_ACTUAL_DATABASE_URL"
  database-password: "REPLACE_WITH_ACTUAL_DATABASE_PASSWORD"
  
  # SSL/TLS Certificates
  tls-cert: "REPLACE_WITH_ACTUAL_TLS_CERTIFICATE"
  tls-key: "REPLACE_WITH_ACTUAL_TLS_PRIVATE_KEY"
  
  # Monitoring and observability
  prometheus-password: "REPLACE_WITH_ACTUAL_PROMETHEUS_PASSWORD"
  grafana-admin-password: "REPLACE_WITH_ACTUAL_GRAFANA_PASSWORD"
  
  # External services
  datadog-api-key: "REPLACE_WITH_ACTUAL_DATADOG_API_KEY"
  sendgrid-api-key: "REPLACE_WITH_ACTUAL_SENDGRID_API_KEY"

---
# Example of using External Secrets Operator (recommended for production)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mysetlist-secret-store
  namespace: mysetlist-production
spec:
  provider:
    vault:
      server: "https://vault.mysetlist.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mysetlist-production"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysetlist-external-secret
  namespace: mysetlist-production
spec:
  refreshInterval: 300s # 5 minutes
  secretStoreRef:
    name: mysetlist-secret-store
    kind: SecretStore
  target:
    name: mysetlist-secrets
    creationPolicy: Owner
  data:
  - secretKey: supabase-url
    remoteRef:
      key: mysetlist/production
      property: SUPABASE_URL
  - secretKey: supabase-anon-key
    remoteRef:
      key: mysetlist/production
      property: SUPABASE_ANON_KEY
  - secretKey: spotify-client-secret
    remoteRef:
      key: mysetlist/production
      property: SPOTIFY_CLIENT_SECRET
  - secretKey: jwt-secret
    remoteRef:
      key: mysetlist/production
      property: JWT_SECRET