apiVersion: v2
name: mysetlist
description: MySetlist - Concert Setlist Voting Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://mysetlist.com
sources:
  - https://github.com/mysetlist/mysetlist
maintainers:
  - name: MySetlist DevOps Team
    email: devops@mysetlist.com
keywords:
  - concert
  - setlist
  - voting
  - music
  - nextjs
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: ingress-nginx
    version: "4.x.x"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
  - name: cert-manager
    version: "1.x.x"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
annotations:
  category: Application